version: '3'
services:
  onedev:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:6610"
      - "${SSH_PORT}:6611"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${DATA_PATH}:/opt/onedev"
    image: 1dev/server:9.2.5
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
