services:
  anqicms:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8001"
    volumes:
      - anqicms-data:/app
    image: "anqicms/anqicms:v3.4.2"
    labels:
      createdBy: "Apps"

volumes:
  anqicms-data:
    name: anqicms-data

networks:
  1panel-network:
    external: true
