services:
  nezha-agent:
    image: "whoer/nezha-agent:0.20.5"
    container_name: ${CONTAINER_NAME} 
    restart: always
    command: --tls -s ${NZ_GRPC_URL} -p ${NZ_CLENT_SECRET} -d
    volumes:
      - /etc:/etc:ro
    network_mode: host
    labels:  
      createdBy: "Apps"