services:
  certd:
    image: "greper/certd:1.27.3"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    volumes:
      - ${DATA_PATH}:/app/data
    ports:
      - "${PANEL_APP_PORT_HTTP}:7001"
    dns:
      - ${DNS_1}
      - ${DNS_2}
    environment:
      - TZ=${TIME_ZONE}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - certd_system_resetAdminPasswd=${RESET_ADMIN_PASSWD}
      - certd_cron_immediateTriggerOnce=${IMMEDIATE_TRIGGER}
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
