services:
  windows:
    image: dockurr/windows:latest
    container_name: ${CONTAINER_NAME}
    environment:
      MANUAL: ${MANUAL}
      DISK_SIZE: ${DISK_SIZE}
      RAM_SIZE: ${RAM_SIZE}
      CPU_CORES: ${CPU_CORES}
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    volumes:
      - ${DATA_PATH}:/storage
      - ${IMAGE_ISO_FILE}:/custom.iso
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - ${PANEL_APP_PORT_HTTP}:8006
      - ${RDP_PORT}:3389/tcp
      - ${RDP_PORT}:3389/udp
    stop_grace_period: 2m
    networks:
      - 1panel-network
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
