services:
  lucky:
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: host
    volumes:
      - ${DATA_PATH}:/goodluck
    image: gdy666/lucky:2.10.0
    labels:  
      createdBy: "Apps"
