services:
  medama:
    image: "ghcr.io/medama-io/medama:v0.4.4"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - medama-data:/app/data
    labels:
      createdBy: "Apps"

volumes:
  medama-data:
    name: medama-data

networks:
  1panel-network:
    external: true
