version: '3'
services:
  siyuan:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:6806"
    volumes:
      - "${DATA_PATH}:/siyuan/workspace"
    user: "1000:1000"
    command: "--workspace=/siyuan/workspace/"
    image: b3log/siyuan:v3.0.13
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
