services:
  certimate:
    image: "usual2970/certimate:v0.2.19"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8090"
    volumes:
      - "${DATA_PATH}:/app/pb_data"
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
