services:
  wewe-rss:
    image: "cooderl/wewe-rss-sqlite:v2.5.0"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:4000"
    environment:
      - DATABASE_TYPE=${DATABASE_TYPE}
      - AUTH_CODE=${AUTH_CODE}
      - FEED_MODE=${FEED_MODE}
      - CRON_EXPRESSION=${CRON_EXPRESSION}
      - MAX_REQUEST_PER_MINUTE=${MAX_REQUEST_PER_MINUTE}
      - SERVER_ORIGIN_URL=${SERVER_ORIGIN_URL}
    volumes:
      - ${DATA_PATH}:/app/data
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
