services:
  beszel:
    image: "henrygd/beszel:0.8.0"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8090"
    volumes:
      - ${DATA_PATH}:/beszel_data
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
