version: '3'
services:
  prometheus:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:9090"
    volumes:
      - "./data:/etc/prometheus"
    image: prom/prometheus:v2.47.2
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
