services:
  atvloadly:
    image: "bitxeno/atvloadly:v0.2.5"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - "${DATA_PATH}:/data"
      - "${DBUS_PATH}:/var/run/dbus"
      - "${AVAHI_DAEMON_PATH}:/var/run/avahi-daemon"
    privileged: ${PRIVILEGED_MODE}
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
