version: '3'
services:
  1panel:
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - ${DATA_PATH}:/opt
    environment:
      - TZ=${TIME_ZONE}
    image: moelin/1panel:v1.8.0
    labels:  
      createdBy: "Apps"
