services:
  easynode:
    image: "chaoszhu/easynode:v2.2.4"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8082"
    volumes:
      - ${DATA_PATH}:/easynode/app/db
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
