services:
  clouddrive:
    image: "cloudnas/clouddrive2:0.7.15"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:19798"
    environment:
      - TZ=${TZ}
      - CLOUDDRIVE_HOME=${CLOUDDRIVE_HOME}
    volumes:
      - ${CLOUD_MOUNTS_PATH}:/CloudNAS:shared
      - ${APP_DATA_PATH}:${CLOUDDRIVE_HOME}
      - ${SHARED_MEDIA_PATH}:/media:shared
    devices:
      - /dev/fuse:/dev/fuse
    pid: "host"
    privileged: ${PRIVILEGED_MODE}
    labels:  
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
