services:
  dpanel:
    image: "dpanel/dpanel:1.3.2-lite"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - ${DOCKER_SOCK_PATH}:/var/run/docker.sock
      - ${DATA_PATH}:/dpanel
    environment:
      - APP_NAME=${APP_NAME}
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
