services:
  verdaccio:
    image: "verdaccio/verdaccio:5.32.2"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    environment:
      - VERDACCIO_APPDIR=${VERDACCIO_APPDIR}
      - VERDACCIO_USER_NAME=${VERDACCIO_USER_NAME}
      - VERDACCIO_USER_UID=${VERDACCIO_USER_UID}
      - VERDACCIO_PORT=${PANEL_APP_PORT_HTTP}
      - VERDACCIO_PROTOCOL=${VERDACCIO_PROTOCOL}
    ports:
      - "${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}"
    volumes:
      - ${STORAGE_PATH}:/verdaccio/storage
      - ${CONFIG_PATH}:/verdaccio/conf
      - ${PLUGINS_PATH}:/verdaccio/plugins
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
