version: '3'
services:
  frp-panel:
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: host
    command: ${COMMAND_LINE}
    image: vaalacat/frp-panel:v0.0.27
    labels:  
      createdBy: "Apps"
