services:
  lrcapi:
    image: "hisatri/lrcapi:1.5.7"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:28883"
    volumes:
      - ${MUSIC_PATH}:/music
    environment:
      - API_AUTH=${API_AUTH}
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
