services:
  peerbanhelper:
    image: "ghostchu/peerbanhelper:v7.2.1"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:9898"
    volumes:
      - "${DATA_PATH}:/app/data"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
    stop_grace_period: ${STOP_GRACE_PERIOD}
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
