version: "3"
services:
  ddns-go:
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: "host"
    volumes:
      - "${DATA_PATH}:/root"
    image: jeessy/ddns-go:v6.3.1
    labels:  
      createdBy: "Apps"
