services:
  bark:
    image: "finab/bark-server:v2.1.7"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}"
    volumes:
      - ${DATA_PATH}:/data
    environment:
      - BARK_SERVER_ADDRESS=${BARK_SERVER_ADDRESS}:${PANEL_APP_PORT_HTTP}
      - BARK_SERVER_URL_PREFIX=${BARK_SERVER_URL_PREFIX}
      - BARK_SERVER_DATA_DIR=${BARK_SERVER_DATA_DIR}
      - BARK_SERVER_DSN=${BARK_SERVER_DSN}
      - BARK_SERVER_SERVERLESS=${BARK_SERVER_SERVERLESS}
      - BARK_SERVER_CERT=${BARK_SERVER_CERT}
      - BARK_SERVER_KEY=${BARK_SERVER_KEY}
      - BARK_SERVER_CASE_SENSITIVE=${BARK_SERVER_CASE_SENSITIVE}
      - BARK_SERVER_STRICT_ROUTING=${BARK_SERVER_STRICT_ROUTING}
      - BARK_SERVER_REDUCE_MEMORY_USAGE=${BARK_SERVER_REDUCE_MEMORY_USAGE}
      - BARK_SERVER_BASIC_AUTH_USER=${BARK_SERVER_BASIC_AUTH_USER}
      - BARK_SERVER_BASIC_AUTH_PASSWORD=${BARK_SERVER_BASIC_AUTH_PASSWORD}
      - BARK_SERVER_PROXY_HEADER=${BARK_SERVER_PROXY_HEADER}
      - BARK_SERVER_CONCURRENCY=${BARK_SERVER_CONCURRENCY}
      - BARK_SERVER_READ_TIMEOUT=${BARK_SERVER_READ_TIMEOUT}
      - BARK_SERVER_WRITE_TIMEOUT=${BARK_SERVER_WRITE_TIMEOUT}
      - BARK_SERVER_IDLE_TIMEOUT=${BARK_SERVER_IDLE_TIMEOUT}
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
