version: '3'
services:
  deeplx:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:1188"
    command: ["/app/deeplx", "-token", "${TOKEN_VAULE}"]
    image: missuo/deeplx:v0.9.4
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
