services:
  cashbook:
    image: "dingdangdog/cashbook:2.0.1"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - ${DATA_PATH}:/app/resources/data
    environment:
      - TOKEN_SALT=${TOKEN_SALT}
      - ENVIRONMENT=${ENVIRONMENT}
      - SERVER_KEY=${SERVER_KEY}
      - DEFAULT_PASSWORD=${DEFAULT_PASSWORD}
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
