services:
  wg-easy:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    environment:
      - WG_HOST=${HOST_ADDRESS}
      - WG_PORT=${WIREGUARD_PORT}
      - PORT=${PANEL_APP_PORT_HTTP}
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS}
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}
      - WG_MTU=${WG_MTU}
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS}
      - WG_PERSISTENT_KEEPALIVE=${WG_PERSISTENT_KEEPALIVE}
      - PASSWORD_HASH=${PASSWORD_HASH}
    volumes:
      - ${DATA_PATH}:/etc/wireguard
    ports:
      - "${WIREGUARD_PORT}:${WIREGUARD_PORT}/udp"
      - "${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    image: "ghcr.io/wg-easy/wg-easy:14"
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
