version: '3'
services:
  slash:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:5231"
    volumes:
      - "${DATA_PATH}:/var/opt/slash"
    image: yourselfhosted/slash:0.4.6
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
