version: "3"
services:
  frps:
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: "host"
    volumes:
        #- "${CONFIG_FILE_PATH}:/etc/frp/frps.ini" #截止5.1.3版本使用ini
        - "${CONFIG_FILE_PATH}:/etc/frp/frps.toml"
    image: "snowdreamtech/frps:latest"
    labels:  
      createdBy: "Apps"
