services:
  radarr:
    image: "linuxserver/radarr:5.16.3"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
    volumes:
      - ${RADARR_CONFIG_PATH}:/config
      - ${MOVIES_PATH}:/movies
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - "${PANEL_APP_PORT_HTTP}:7878"
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
